from enum import IntEnum


class Limits(IntEnum):
    MAX_LEN_EMAIL_FIELD = 256
    MAX_LEN_USERS_CHARFIELD = 150
    DESIGNATION = 200
    MIN_COOKING_TIME = 1
    MAX_COOKING_TIME = 300
    MIN_AMOUNT_INGREDIENTS = 1
    MAX_AMOUNT_INGREDIENTS = 20
